<?xml version="1.0" encoding="UTF-8"?>
<xmldoc>
  <copyright>SAME AS NELSON SOFTWARE</copyright>

  <language>en_US</language>
  <keyword>throwAsCaller</keyword>
  <short_description>Throw exception as if occurs within calling function.</short_description>

  <syntax>
    <syntax_item>throwAsCaller(MException)</syntax_item>
  </syntax>

  <param_input>
    <param_input_item>
      <param_name>MException</param_name>
      <param_description>MException object</param_description>
    </param_input_item>
  </param_input>

  <description>
    <p>It throws an exception as if it occurs within the calling function.</p>
  </description>


  <used_function></used_function>
  <bibliography></bibliography>

<examples>

  <example_item>
    <example_item_type>nelson</example_item_type>
    <example_item_description></example_item_description>
    <example_item_data><![CDATA[
function test_throwAsCaller()
  ME = MException('n:m', 'your error')
  throwAsCaller(ME)]]>
    </example_item_data>
  </example_item>

</examples>

  <see_also>
    <see_also_item>
      <link linkend="${error_manager}MException">MException</link>
    </see_also_item>
    <see_also_item>
      <link linkend="${error_manager}rethrow">rethrow</link>
    </see_also_item>
    <see_also_item>
      <link linkend="${error_manager}throw">throw</link>
    </see_also_item>

  </see_also>

  <history>
    <history_item>
      <history_version>1.0.0</history_version>
      <history_description>initial version</history_description>
    </history_item>
  </history>

  <authors>
    <author_item>Allan CORNET</author_item>
  </authors>
</xmldoc>


